name: Release

on:
  push:
    branches: ["release/**", "release/*"]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
      prerelease:
        description: 'Mark as prerelease'
        type: boolean
        default: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Get version from branch name
        if: github.event_name != 'workflow_dispatch'
        id: get-version
        run: |
          branch_name="${GITHUB_REF#refs/heads/}"
          version=$(echo "$branch_name" | grep -oP 'release/v?\K([0-9]+\.[0-9]+\.[0-9]+)')
          echo "version=$version" >> $GITHUB_OUTPUT
          
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: kit-build
          path: build
          
      - name: Download spec diffs
        uses: actions/download-artifact@v4
        with:
          name: spec-diffs
          path: spec-check
          
      - name: Download release notes
        uses: actions/download-artifact@v4
        with:
          name: release-notes
          path: release-notes
          
      - name: Create Release
        uses: genesis-community/genesis-kit-release-action@v1
        with:
          kit_name: your-kit-name
          version: ${{ github.event.inputs.version || steps.get-version.outputs.version }}
          prerelease: ${{ github.event.inputs.prerelease || false }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          notification_webhook: ${{ secrets.NOTIFICATION_WEBHOOK }}
          notification_username: ${{ secrets.NOTIFICATION_USERNAME }}
          notification_password: ${{ secrets.NOTIFICATION_PASSWORD }}